### ISSUE TITLE
express 4.16.x 부터는 body-parser 포함되서 따로 설치 안해도 됨!!

### ISSUE THREAD

**Issue by YongHoonJJo** [AcrylicShrimp/remf-server#1]
관련 링크 참고 ㅎㅎ
[https://expressjs.com/en/4x/api.html#express-json-middleware](https://expressjs.com/en/4x/api.html#express-json-middleware)

**Comment by AcrylicShrimp** [comment]
앗 진짜네요 ㅎㅎ 감사합니다!
